<?php
// module/Company/view/Company/Company/add.phtml:

$title = 'Add new job';
$this->headTitle($title);
?>

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('company/add', array('action' => 'add')));
//$form->prepare();

echo '<div class="label">';
echo '<h3 class ="ui-widget-header"></h3>';
//    echo $this->escapeHtml($title);
//echo '</h3>';

echo'<form class="form-horizontal">';


  echo '<div class="control-group">';
    echo '<label class="control-label">Title</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('title'));
        echo '</div>';
    echo '</div>';
 
    
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Company name</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('company'));
//        echo '</div>';
//    echo '</div>';
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Close Date</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('closeDate'));
//        echo '</div>';
//    echo '</div>';
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Messag</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('message'));
//        echo '</div>';
//    echo '</div>';
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Tel:</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('phoneNumber'));
//        echo '</div>';
//    echo '</div>';
//    echo '<div class="control-group">';
//    echo '<label class="control-label">E-mail</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('email'));
//        echo '</div>';
//    echo '</div>';
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Web sit:</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('web'));
//        echo '</div>';
//    echo '</div>';
    echo '<div class="control-group">';
        echo '<div class="controls">';
            echo $this->formSubmit($form->get('submit'));
        echo '</div>';
    echo '</div>';
echo '</form>';
echo '</div>';


?>
<!-- <style>.labels{text-align: right}</style> -->
